spring.application.name=ProyectoConecta

spring.jpa.hibernate.ddl-auto=create-drop


spring.profiles.active=pgsql, dev

spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose.yml